# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    ai_responsive.locale_listener:
        class: AI\ResponsiveBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    ai_responsive.url_listener:
        class: AI\ResponsiveBundle\EventListener\URLListener
        arguments: ["%url%"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    ai_responsive.twig_extension:
        class: AI\ResponsiveBundle\Extension\TwigExtension
        public: false
        tags:
            - { name: twig.extension }

    global_functions:
        class: AI\ResponsiveBundle\Controller\GlobalController
        arguments:
            container: "@service_container"

    dbconnector:
        class: AI\ResponsiveBundle\Service\DBConnector
        arguments: [%database_host%, %database_user%, %database_password%, %sales_db%, %data_db%]

    app.form.handler.registration:
        class: AI\UserBundle\Form\Handler\RegistrationFormHandler
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator", "@dbconnector"]
        scope: request
        public: false

    ai.role_listener:
        class: AI\ResponsiveBundle\EventListener\RoleListener
        arguments: ["@dbconnector"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
