<h1>Baromètre AsiaInspection du troisième trimestre : quand la recherche de coûts plus bas en Asie se fait aux dépends de la sécurité</h1>
<p><b>Shenzhen, Chine, 4 octobre 2013</b> - AsiaInspection, l'un des fournisseurs majeurs dans le domaine du contrôle qualité pour les entreprises importatrices de produits en provenance d'Asie, d'Afrique, d'Europe du Sud et d'Amerique latine, annonce aujourd'hui la publication de son baromètre pour le troisième trimestre 2013. Ce baromètre trimestriel est un résumé d’indicateurs industriels et commerciaux lié au contrôle qualité.</p>

<h2 style="font-size:18px;">Forte hausse de la demande d’audits d'éthique, notamment en provenance des importateurs nord-américains</h2>
<div style="padding:0px 0px 15px 15px;width:357px;float:right;">
	<iframe src="https://www.slideshare.net/slideshow/embed_code/26849269?rel=0" width="354" height="300" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC;border-width:1px 1px 0;margin-bottom:5px" allowfullscreen> </iframe>
</div>
<p style="text-align:justify;">Depuis l'effondrement de l'usine Rana Plaza en avril 2013, les chiffres d'AsiaInspection indiquent une augmentation de <b>+52%</b> des demandes d’audits de responsabilité sociale des usines en Asie au troisième trimestre 2013 par rapport au troisième trimestre 2012, avec un pic de <b>+167%</b> au Bangladesh. Cette croissance s'est maintenue tout au long du troisième trimestre et nous avons connu au mois de septembre la plus forte demande d'audits jamais enregistrée par AsiaInspection. La plus forte augmentation provient des importateurs nord-américains, soit <b>+72%</b> pour la période concernée.</p>
<p style="text-align:justify;">Cette forte demande en Amérique du Nord a été stimulée par la création de l'Alliance for Bangladesh Worker Safety (Alliance pour la sécurité des ouvriers Bangladais), formée par un ensemble de distributeurs, de marques et d'entreprises du secteur de l'habillement.  Des sociétés comme Target, Gap Walmart, Nordstrom, Macy's et Kohl's se sont engagées à auditer 100 % des entreprises de l'alliance d'ici 2014.</p>
<div style="clear:both;"></div>

<h2 style="font-size:18px;">En Chine, les productions s'éloignent de la côte et sont moins conformes aux standards sociaux</h2>
<p>Alors que les coûts n'ont cessé de croître dans les zones industrielles développées de Chine comme les provinces de Guangdong, Jiangsu, Shandong et Zhejiang, les productions se déplacent vers l'intérieur des terres, où la main-d'œuvre peut coûter jusqu'à 70 % moins cher.</p>
<p>AsiaInspection a analysé les données des audits d'éthique effectués en Chine. L'ensemble de ces audits répond aux standards internationaux SA 8000 ou Sedex (SMETA) pour la conformité sociale et éthique. Pour cette étude, les notes attribuées sont comprises entre 0 et 10, une note de 10 correspondant à une conformité totale.</p>
<p>La conformité moyenne pour la Chine en 2013 est de 6,22/10.  Les usines situées dans l'ouest de la Chine, pour lesquelles les acheteurs recherchent les coûts les plus faibles, ont obtenu les notes les plus faibles, avec une moyenne de 5,91/10. Le plus grand centre industriel chinois, la province de Guangdong, a obtenu la meilleure note, avec une moyenne de 7,1/10, suivie par le nord du pays (6,12/10) et par les provinces exportatrices de la côte Est, à 6,08/10.</p>
<p>« Les acheteurs doivent prendre conscience que le fait de déplacer leur production vers des régions moins chères se fait probablement au détriment des conditions sociales de travail », explique Sébastien Breteau, président d'AsiaInspection. « Les événements récents en Asie ont montré que le risque social et de sécurité est très réel sur l'ensemble de la chaîne logistique.  La recherche de la réduction des coûts doit être accompagnée d'une approche holistique de la surveillance et de l'audit de ses fournisseurs. »</p>

<h2 style="font-size:18px;">Sécurité alimentaire en Chine: le manque de contrôles permet de nouveaux cas de maladies et décès</h2>
<p>L’industrie alimentaire chinoise est encore frappée ce trimestre de plusieurs scandales : 20 tonnes de faux bœuf saisis, de l'arsenic retrouvé par l'organisme suédois de surveillance de la sécurité alimentaire dans des remèdes chinois à base de plantes et du formaldéhyde identifié dans du poisson chinois vendu dans des supermarchés américains.</p>
<p>Selon l'organisme américain Centers for Disease Control and Prevention (Centres pour le contrôle et la prévention des maladies, CDC), 48 millions d'Américains ont contracté une maladie portée par des aliments en 2011, parmi lesquels 3 037 en sont décédés.  Chaque année, plus de 10 millions de conteneurs de denrées alimentaires sont importés aux États-Unis, dont plus de 60 % en provenance de pays en voie de développement, en particulier de la Chine.  La Food and Drugs Administration (FDA) a reconnu qu'elle inspecte seulement 1,5 % des aliments importés, parmi lesquels elle rejette tout de même 16 000 conteneurs par an.</p>
<p>Malgré ces chiffres alarmants, le ministère de l'Agriculture américain vient d’assouplir la législation sur l'importation des denrées alimentaires de Chine. Désormais, les poulets abattus aux États-Unis et au Canada peuvent être transformés en Chine, puis renvoyés aux États-Unis pour la consommation.</p>
<p>Il existe un besoin croissant de contrôle de la chaîne alimentaire, comme le montre l'augmentation de <b>+93%</b> des inspections alimentaires rapportée par AsiaInspection au troisième trimestre 2013 par rapport au troisième trimestre 2012, avec une augmentation de <b>+57%</b>. en Chine. L'augmentation de <b>+89%</b> du nombre d'audits d'hygiène alimentaire montre également que l’industrie se soucie de plus en plus de la conformité des usines asiatiques aux normes internationales.</p>

<h2 style="font-size:18px;">À propos d'AsiaInspection - Your Eyes in the Supply Chain!&trade;</h2>
<p>AsiaInspection (AI) est un acteur leader du contrôle qualité qui s'associe avec des marques, distributeurs et importateurs internationaux pour sécuriser et gérer leur chaîne d’approvisionnement en Asie, Afrique, Europe du Sud et Amérique latine. Avec un outil unique de gestion du contrôle qualité en ligne, AI offre des services d'inspection de produits, d'audit industriels et de test en laboratoires à 2 700 clients à travers 20 bureaux dans le monde.</p>

<p>
	<b>Contact Presse</b>
	<br />Michael Mesarch
	<br />Tél: (+86) 755 2223 9888
	<br />E-mail: <a href="mailto:press@asiainspection.com">press@asiainspection.com</a>
</p>