<?php

namespace AI\ResponsiveBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegisterRepository extends EntityRepository
{
}
